type: unmanaged

cluster:
  name: ""
  kubernetesVersion: v1.35.0
  podCidrBlocks:
    - 192.168.0.0/16
  serviceCidrBlocks: []
  vsphere:
    server: ""
    thumbprint: ""
    datacenter: ""
    datastore: ""
    folder: ""
    resourcePool: ""
    network: ""
    template: ""
    cloneMode: fullClone
    powerOffMode: trySoft
    os: Linux
    identity:
      username: ""
      password: ""
    controlPlaneEndpoint:
      host: ""
      port: 6443
    kubeVip:
      enabled: true
      address: ""
      image: ghcr.io/kube-vip/kube-vip:v0.8.0

addons:
  cni:
    enabled: true
    podCidr: 192.168.0.0/16
  cpi:
    enabled: true
    image: registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.35.0

controlPlane:
  replicas: 1
  sshAuthorizedKeys: []
  machine:
    numCPUs: 2
    memoryMiB: 8192
    diskGiB: 25

workers:
  defaults:
    replicas: 0
    sshAuthorizedKeys: []
    spec:
      numCPUs: 2
      memoryMiB: 8192
      diskGiB: 25
      cloneMode: fullClone
      powerOffMode: trySoft
      os: Linux
      network:
        devices:
          - dhcp4: true
            dhcp6: false
            networkName: ""
  groups: {}
