{{- if .Values.identity -}}
kind: AzureClusterIdentity
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: default # Using same name as identity created by the management cluster, so it can be easily referenced.
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  type: ServicePrincipal
  allowedNamespaces: {}
  tenantID: {{ .Values.identity.tenantId }}
  clientID: {{ .Values.identity.clientId }}
  clientSecret:
    name: default-identity-secret
    namespace: {{ .Release.Namespace }}
---
kind: Secret
apiVersion: v1
metadata:
  name:  default-identity-secret
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.identity.clientSecret | b64enc | quote }}
{{- end }}
