{{- if .Values.identity -}}
kind: AzureClusterIdentity
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: default-identity
  namespace: bootstrap # Always create it in bootstrap namespace, no matter if it is management or workload cluster.
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  type: ServicePrincipal
  allowedNamespaces: {}
  tenantID: {{ .Values.identity.tenantId }}
  clientID: {{ .Values.identity.clientId }}
  clientSecret:
    name: default-identity-secret
    namespace: bootstrap
---
kind: Secret
apiVersion: v1
metadata:
  name:  default-identity-secret
  namespace: bootstrap
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.identity.clientSecret | b64enc | quote }}
{{- end }}
