{{- if .Values.identity -}}
kind: AzureClusterIdentity
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  # At the moment it is created with the same name and namespace as identity in the management cluster.
  # TODO: Once we will be able to check management cloud name we can update this to use different name and chart release namespace.
  name: default
  namespace: bootstrap
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  type: ServicePrincipal
  allowedNamespaces: {}
  tenantID: {{ .Values.identity.tenantId }}
  clientID: {{ .Values.identity.clientId }}
  clientSecret:
    name: default-identity-secret
    namespace: bootstrap
---
kind: Secret
apiVersion: v1
metadata:
  name:  default-identity-secret
  namespace: bootstrap
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret: {{ .Values.identity.clientSecret | b64enc | quote }}
{{- end }}
