controlPlane:
  sshAuthorizedKeys:
{% if context.sshPublicKey -%}
  - {{ context.sshPublicKey }}
{% endif -%}

workers:
  defaults:
    sshAuthorizedKeys:
{% if context.sshPublicKey -%}
  - {{ context.sshPublicKey }}
{% endif -%}
