apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: basic-auth-prom
  namespace: infra
spec:
  template:
    username: plrl
    password: {% raw %}"{{ 32 | randAlphaNum }}"{% endraw %}
  destinations:
  - name: basic-auth-prom
    namespace: infra
  - name: basic-auth-prom
    namespace: plrl-deploy-operator
