apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: keda
  namespace: apps
spec:
  template:
    name: keda
    namespace: keda
    helm:
      url: https://kedacore.github.io/charts
      chart: keda
      version: 2.19.0
