apiVersion: dbs.plural.sh/v1alpha1
kind: ElasticsearchCredentials
metadata:
  name: elasticsearch
  namespace: elastic
  annotations:
    deployment.plural.sh/sync-wave: "5"
spec:
  url: http://elasticsearch-es-http.elastic.svc:9200
  username: plrl
  passwordSecretKeyRef:
    name: plrl-elastic-user
    key: password
