apiVersion: dbs.plural.sh/v1alpha1
kind: ElasticsearchILMPolicy
metadata:
  name: plrl-logs
  namespace: elastic
  annotations:
    deployment.plural.sh/sync-wave: "6"
spec:
  name: plrl-logs
  credentialsRef:
    name: elasticsearch
  definition:
    policy:
      phases:
        warm:
          min_age: 10d
          actions:
            forcemerge:
              max_num_segments: 1
        delete:
          min_age: 30d
          actions:
            delete: {}
