apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: cloudnative-pg
spec:
  serviceRef:
    name: cloudnative-pg
    namespace: cnpg-system
  scope:
    clusterTags:
      platform: k8s
  template:
    repositoryRef:
      name: infra
      namespace: infra
    git:
      ref: main
      folder: helm/cloudnative-pg
    helm:
      chart: cloudnative-pg
      url: https://cloudnative-pg.github.io/charts
      version: 0.29.0
      values:
        replicaCount: 1
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
