apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: valkey-users-{{ context.cluster }}
  namespace: infra
spec:
  template:
    password: {% raw %}"{{ 48 | randAlphaNum }}"{% endraw %}
  destinations:
  - name: valkey-users-{{ context.cluster }}
    namespace: infra
  - name: valkey-users-{{ context.cluster }}
    namespace: plrl-deploy-operator
