apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opa-gatekeeper
  namespace: apps
spec:
  interval: 5m0s
  url: https://open-policy-agent.github.io/gatekeeper/charts