## managed or unmanaged, currently only managed is supported
type: managed

cluster:
  ## The name of the cluster
  name: plural-workload
  ## The version of Kubernetes to deploy
  kubernetesVersion: 1.24.17
  ## The cidr blocks for pods
  podCidrBlocks:
    - 192.168.0.0/16 # TODO: shouldn't this also be getting propagated to things like what `.Values.cluster.aws.network.vpc.cidrBlock` is setting?
  ## The cidr blocks for services
  serviceCidrBlocks: [ ] # TODO: check if we should be setting this
  # Project is the id of the project to deploy the cluster to.
  project: ""
  # Region represents the location (region or zone) in which the GKE cluster will be created.
  # Examples: "europe-central2" TODO: add more examples
  region: ""
  # AdditionalLabels is an optional set of tags to add to GCP resources managed by the GCP provider,
  # in addition to the ones added by default.
  additionalLabels:
    managed-by: plural
  # EnableAutopilot indicates whether to enable autopilot for this GKE cluster.
  #
  # Note: Autopilot enabled clusters are not supported at this time.
  enableAutopilot: false
  # EnableWorkloadIdentity allows enabling workload identity during cluster creation when
  # EnableAutopilot is disabled. It allows workloads in your GKE clusters to impersonate
  # Identity and Access Management (IAM) service accounts to access Google Cloud services.
  # Ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
  enableWorkloadIdentity: true
  # ReleaseChannel is the release channel of the GKE cluster
  # One of: unspecified, rapid, regular, stable
  releaseChannel: unspecified
  # AddonsConfig is a configuration for the addons that can be automatically spun up in the
  # cluster, enabling additional functionality.
  addonsConfig:
    # HttpLoadBalancingEnabled tracks whether the HTTP Load Balancing controller is enabled in the cluster.
    # When enabled, it runs a small pod in the cluster that manages the load balancers.
    httpLoadBalancingEnabled: true
    # HorizontalPodAutoscalingEnabled tracks whether the Horizontal Pod Autoscaling feature is enabled in the cluster.
    # When enabled, it ensures that metrics are collected into Stackdriver Monitoring.
    horizontalPodAutoscalingEnabled: true
    # NetworkPolicyEnabled tracks whether the addon is enabled or not on the Master,
    # it does not track whether network policy is enabled for the nodes.
    networkPolicyEnabled: false
    # GcpFilestoreCsiDriverEnabled tracks whether the GCP Filestore CSI driver is enabled for this cluster.
    gcpFilestoreCsiDriverEnabled: true
  # Network encapsulates all things related to the GCP network.
  network:
    name: plural-workload
    # AutoCreateSubnetworks: When set to true, the VPC network is created
    # in "auto" mode. When set to false, the VPC network is created in
    # "custom" mode.
    #
    # An auto mode VPC network starts with one subnet per region. Each
    # subnet has a predetermined range as described in Auto mode VPC
    # network IP ranges.
    #
    # Note: Only auto mode is supported at this time.
    autoCreateSubnetworks: true
    # The desired datapath provider for this cluster.
    # One of:
    # - UNSPECIFIED - default value
    # - LEGACY_DATAPATH - uses the IPTables implementation based on kube-proxy
    # - ADVANCED_DATAPATH - uses the eBPF based GKE Dataplane V2 with additional features
    datapathProvider: ADVANCED_DATAPATH
  subnets:
    - name: plural-subnetwork
      # CidrBlock is the range of internal addresses that are owned by this
      # subnetwork. Provide this property when you create the subnetwork. For
      # example, 10.0.0.0/8 or 192.168.0.0/16. Ranges must be unique and
      # non-overlapping within a network. Only IPv4 is supported. This field
      # can be set only at resource creation time.
      cidrBlock: 10.0.32.0/20
      # Description is an optional description associated with the resource.
      description: ""
      # SecondaryCidrBlocks defines secondary CIDR ranges,
      # from which secondary IP ranges of a VM may be allocated
      secondaryCidrBlocks: { }
      # PrivateGoogleAccess defines whether VMs in this subnet can access
      # Google services without assigning external IP addresses
      privateGoogleAccess: true
      # EnableFlowLogs: Whether to enable flow logging for this subnetwork.
      # If this field is not explicitly set, it will not appear in get
      # listings. If not set the default behavior is to disable flow logging.
      enableFlowLogs: false
      # Purpose: The purpose of the resource.
      # If unspecified, the purpose defaults to PRIVATE_RFC_1918.
      # The enableFlowLogs field isn't supported with the purpose field set to INTERNAL_HTTPS_LOAD_BALANCER.
      # One of:
      # - INTERNAL_HTTPS_LOAD_BALANCER - Subnet reserved for Internal HTTP(S) Load Balancing.
      # - PRIVATE - Regular user created or automatically created subnet.
      # - PRIVATE_RFC_1918 - Regular user created or automatically created subnet.
      # - PRIVATE_SERVICE_CONNECT - Subnetworks created for Private Service Connect in the producer network.
      # - REGIONAL_MANAGED_PROXY - Subnetwork used for Regional Internal/External HTTP(S) Load Balancing.
      purpose: PRIVATE_RFC_1918

workers:
  defaults:
    #####################################
    ###        WORKER DEFAULTS        ###
    #####################################
    replicas: 0
    labels: { }
    annotations:
      cluster.x-k8s.io/replicas-managed-by: external-autoscaler
    isMultiAZ: false # if false, will create a node group per AZ # TODO: false currently unsupported so all node groups set this to true
    spec:
      scaling:
        maxCount: 9
        minCount: 1
      management:
        autoRepair: true
        autoUpgrade: true
      kubernetesLabels:
        plural.sh/capacityType: ON_DEMAND
        plural.sh/performanceType: BURST
      kubernetesTaints: [ ]
      additionalLabels: { }
      providerIDList: [ ]
      machineType: e2-standard-2
      diskSizeGb: 50
      diskType: pd-standard
      spot: false
      preemptible: false
      imageType: COS_CONTAINERD
  #############################
  ###        WORKERS        ###
  #############################
  groups: { }