apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: cluster-{{ context.fleet }}-{{ context.tier }}
spec:
  name: cluster-{{ context.fleet }}-{{ context.tier }}
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  configuration:
    version: '1.8'
  repositoryRef:
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
  git:
    ref: main
    folder: terraform/modules/clusters/aws
  variables:
    cluster: {{ context.name }}
    fleet: {{ context.fleet }}
    tier: {{ context.tier }}
    region: {{ context.region }}
    {% raw %} 
    kubernetes_version: {{ context.kubernetesVersion }}
    {% endraw %}
---
apiVersion: deployments.plural.sh/v1alpha1
kind: Cluster
metadata:
  name: {{ context.name }}
spec:
  handle: {{ context.name }}