{{- if .Values.credentials.server -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-api-provider-vsphere.credentialsSecretName" . }}
  namespace: {{ include "cluster-api-provider-vsphere.namespace" . }}
  labels:
    {{- include "cluster-api-provider-vsphere.labels" . | nindent 4 }}
type: Opaque
stringData:
  VSPHERE_USERNAME: {{ .Values.credentials.username | quote }}
  VSPHERE_PASSWORD: {{ .Values.credentials.password | quote }}
  {{- if .Values.credentials.server }}
  VSPHERE_SERVER: {{ .Values.credentials.server | quote }}
  {{- end }}
  {{- if .Values.credentials.thumbprint }}
  VSPHERE_TLS_THUMBPRINT: {{ .Values.credentials.thumbprint | quote }}
  {{- end }}
{{- end }}
