apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: sealed-secrets
  namespace: apps
spec:
  template:
    name: sealed-secrets
    namespace: sealed-secrets
    helm:
      url: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      version: 2.20.0
      values:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
        podSecurityContext:
          runAsNonRoot: true
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
