apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  template:
    namespace: ingress-nginx
    git:
      ref: main
      folder: helm
    repositoryRef:
      name: infra # if you check in `bootstrap/setup.yaml` you should find the custom resource this points to
      namespace: infra
    helm:
      version: x.x.x
      chart: ingress-nginx
      url: https://kubernetes.github.io/ingress-nginx
      valuesFiles:
      - ingress-nginx.yaml