apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: grafana
spec:
  name: grafana
  icon: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/2783a06b-8317-4998-8c5d-18bcdc2a3c6c/grafana.png?v=63849313526
  identifier: mgmt
  documentation: |
    Sets up a Grafana instance backed by postgres
  creates:
    git:
      ref: main # TODO set to main
      folder: catalogs/devops/grafana
    templates:
    - source: README.md
      destination: documentation/grafana/README.md
      external: true
    - source: grafana.yaml.liquid
      destination: "helm/grafana/{{ context.cluster }}/grafana.yaml.liquid"
      external: true
    - source: servicedeployment.yaml.liquid
      destination: "bootstrap/apps/grafana/{{ context.cluster }}/servicedeployment.yaml"
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: devops
  scmConnectionRef:
    name: plural # you'll need to add this ScmConnection manually before this is functional
  title: "Grafana setup ({{ context.cluster }})"
  message: |
    Sets up Grafana on {{ context.cluster }} cluster.
  configuration:
  - name: cluster
    type: STRING
    documentation: the cluster you want to deploy to
  - name: hostname
    type: STRING
    documentation: the hostname of the grafana instance
