apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: grafana
spec:
  name: grafana
  icon: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/2783a06b-8317-4998-8c5d-18bcdc2a3c6c/grafana.png?v=63849313526
  identifier: mgmt
  documentation: |
    Sets up a Grafana instance backed by postgres
  creates:
    git:
      ref: main
      folder: catalogs/devops/grafana
    templates:
    - source: helm/grafana.yaml.liquid
      destination: "helm/grafana/grafana.yaml.liquid"
      external: true
    - source: servicedeployment.yaml.liquid
      destination: "bootstrap/apps/grafana/{{ context.cluster }}/servicedeployment.yaml"
      external: true
    - source: terraform/{{ context.cloud }}
      destination: terraform/apps/grafana
      external: true
    - source: grafana-stack.yaml.liquid
      destination: "bootstrap/apps/grafana/{{ context.cluster }}/stack.yaml"
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: devops
  scmConnectionRef:
    name: plural # you'll need to add this ScmConnection manually before this is functional
  title: "Grafana setup ({{ context.cluster }})"
  message: |
    Sets up Grafana on {{ context.cluster }} cluster.
  configuration:
  - name: cloud
    type: ENUM
    documentation: the cloud provider you'll be deploying grafana to
    values:
    - aws
  - name: cluster
    type: CLUSTER
    documentation: the cluster you want to deploy to
  - name: hostname
    type: STRING
    documentation: the hostname of the grafana instance
  - name: pluralCloud
    type: BOOL
    documentation: whether you're deploying to plural cloud (we will auto-configure a prometheus datasource for you if so)
