apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: kubecost
spec:
  name: kubecost
  icon: https://github.com/pluralsh/plural-artifacts/blob/main/kubecost/plural/icons/kubecost.png?raw=true
  identifier: mgmt
  documentation: |
    Sets up Kubecost Kubernetes Cost Monitoring and Management.
  creates:
    git:
      ref: sebastian/prod-2981-set-up-catalog-pipeline # TODO set to main
      folder: catalogs/devops/kubecost
    templates:
    - source: README.md
      destination: documentation/kubecost/README.md
      external: true
    - source: kubecost.yaml.liquid
      destination: "helm/kubecost/kubecost.yaml.liquid"
      external: true
    - source: extractor.yaml.liquid
      destination: services/kubecost/extractor.yaml
      external: true
    - source: global.yaml.liquid
      destination: "bootstrap/apps/kubecost/globalservice.yaml"
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: devops
  scmConnectionRef:
    name: plural # you'll need to add this ScmConnection manually before this is functional
  title: "Global Kubecost Setup"
  message: |
    Sets up Kubecost global service with KubecostExtractor resources to publish back to plural
  configuration: []
