apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: loki
spec:
  name: loki
  icon: https://raw.githubusercontent.com/grafana/loki/main/docs/sources/logo.png
  identifier: mgmt
  documentation: |
    Sets up Loki log aggregation in single-binary mode with persistent
    filesystem storage and a ClusterIP gateway.
  creates:
    git:
      ref: main
      folder: catalogs/devops/loki
    templates:
    - source: README.md
      destination: documentation/loki/README.md
      external: true
    - source: loki.yaml
      destination: bootstrap/apps/loki/loki.yaml
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: devops
  scmConnectionRef:
    name: plural # you'll need to add this ScmConnection manually before this is functional
  title: Loki setup
  message: |
    Sets up Loki log aggregation in the management cluster.

    Plural Service: mgmt/apps
  configuration: []
