apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: plrl-elastic-user
  namespace: infra
spec:
  template:
    username: plrl
    password: {% raw %}"{{ 32 | randAlphaNum }}"{% endraw %}
    roles: superuser
  destinations:
  - name: plrl-elastic-user
    namespace: elastic
  - name: plrl-elastic-user
    namespace: infra
  - name: plrl-elastic-user
    namespace: plrl-deploy-operator
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: elastic-roles
  namespace: infra
spec:
  template:
    roles.yml: |-
      logstash_user:
        cluster: [ "manage_index_templates", "monitor", "manage_ilm" ]
        indices:
        - names: [ 'plrl-logs*', '*beats*' ]
          privileges: [ "write","create","create_index","manage","manage_ilm" ]
  destinations:
  - name: elastic-roles
    namespace: elastic
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: plrl-logstash-user
  namespace: infra
spec:
  template:
    username: logstash
    password: {% raw %}"{{ 32 | randAlphaNum }}"{% endraw %}
    roles: logstash_user
  destinations:
  - name: plrl-logstash-user
    namespace: elastic
  - name: plrl-logstash-user
    namespace: infra