apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: plrl-elastic-user
  namespace: infra
spec:
  template:
    username: plrl
    password: {% raw %}"{{ 32 | randAlphaNum }}"{% endraw %}
    roles: superuser
  destinations:
  - name: plrl-elastic-user
    namespace: elastic
  - name: plrl-elastic-user
    namespace: infra
  - name: plrl-elastic-user
    namespace: plrl-deploy-operator