apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: logstash
  namespace: infra
spec:
  namespace: elastic
  repositoryRef:
    name: infra
    namespace: infra
  git:
    folder: services/logstash
    ref: main
  configurationRef:
    name: plrl-logstash-user
    namespace: infra
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: infra
---
apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: logstash
  namespace: infra
spec:
  serviceRef:
    name: logstash
    namespace: infra