apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: netobserv-flowcollector
  namespace: apps
spec:
  template:
    namespace: netobserv
    git:
      folder: services/netobserv
      ref: main
    repositoryRef:
      kind: GitRepository
      name: infra
      namespace: infra
