apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: netobserv
  namespace: apps
spec:
  template:
    namespace: netobserv
    repositoryRef:
      kind: GitRepository
      name: infra
      namespace: infra
    helm:
      url: https://pluralsh.github.io/console
      chart: network-observability-operator
      version: 'x.x.x'
