apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: netobserv
  namespace: apps
spec:
  template:
    name: netobserv
    namespace: netobserv
    helm:
      url: https://maciaszczykm.github.io/helm-charts # TODO: https://pluralsh.github.io/console.
      chart: network-observability-operator
      version: 'x.x.x'
