apiVersion: deployments.plural.sh/v1alpha1
kind: GlobalService
metadata:
  name: external-secrets
  namespace: apps
spec:
  template:
    name: external-secrets
    namespace: external-secrets
    helm:
      url: https://charts.external-secrets.io
      chart: external-secrets
      version: 2.4.1
