apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: plrl-03-wordpress
  namespace: examples
spec:
  repositoryRef:
    kind: GitRepository
    name: kustomize
    namespace: examples
  git:
    folder: services/examples/kustomize-stack-with-liquid
    ref: main
  configuration:
    wordpressTag: "4.8-apache"
    mysqlTag: "5.6"
  clusterRef:
    name: mgmt
    namespace: examples