apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: osartifact
spec:
  name: osartifact
  icon: https://user-images.githubusercontent.com/2420543/193010398-72d4ba6e-7efe-4c2e-b7ba-d3a826a55b7d.png
  identifier: mgmt
  documentation: |
    Sets up an osartifact CRD to initialize Kairos image creation
  creates:
    git:
      ref: catalog/add-edge # TODO change to main
      folder: catalogs/edge/osartifact
    templates:
    - source: services
      destination: "services/apps/osartifact/{{ context.cluster }}/{{ context.name }}"
      external: true
    - source: "terraform/{{ context.cloud }}"
      destination: "terraform/apps/osartifact/{{ context.cluster }}/{{ context.name }}"
      external: true
    - source: osartifact.yaml
      destination: "bootstrap/apps/osartifact/{{ context.cluster }}/{{ context.name }}/osartifact.yaml"
      external: true
    - source: osartifact-raw.yaml
      destination: "bootstrap/apps/osartifact/{{ context.cluster }}/{{ context.name }}/osartifact-raw.yaml"
      external: true
    - source: osartifact-stack.yaml
      destination: "bootstrap/apps/osartifact/{{ context.cluster }}/{{ context.name }}/osartifact-stack.yaml"
      external: true
    - source: helm
      destination: "helm/osartifact/{{ context.cluster }}/{{ context.name }}"
      external: true
    - source: README.md
      destination: documentation/osartifact/README.md
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: edge
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Setting up OSArtifact CRD on cluster {{ context.cluster }}"
  message: Will create an OSArtifact CRD to initialize Kairos image creation.
  configuration:
  - name: cluster
    type: CLUSTER
    documentation: Handle of the cluster where osbuilder is installed.
    default: mgmt
  - name: cloud
    type: ENUM
    default: aws
    documentation: Cloud used to run infrastructure stack.
    values:
      - aws
  - name: project
    type: PROJECT
    documentation: Name of the Plural project that will be attached to the device bootstrap token.
    default: default
  - name: name
    type: STRING
    documentation: Name that helps you better track result images and devices.
  - name: image
    type: STRING
    documentation: The base image to use for building custom Kairos image.
    default: "quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1"
  - name: device
    type: ENUM
    documentation: The target device that will be used to run the OS
    default: rpi4
    values:
      - rpi4
  - name: username
    type: STRING
    documentation: Username that will be used to access the device over SSH.
    default: plural
  - name: repository
    type: STRING
    documentation: Name of existing repository where images should be stored. If not provided it will be inferred from name in a format "pluralos-{{ name }}".
    optional: true

  # User-provided registry options
  - name: useExistingRegistry
    type: BOOL
    documentation: Whether your existing container registry should be used. If set to false, osbuilder must be deployed with self-hosted registry to infer configuration.
    default: 'true'
  - name: isECRRegistry
    type: BOOL
    documentation: Whether your existing container registry is hosted on ECR.
    default: 'false'
    optional: true
    condition:
      field: useExistingRegistry
      operation: EQ
      value: 'true'

  - name: registry
    type: STRING
    documentation: Docker registry DNS name where we should export packed ISO images. Optional when using ECR registry.
    optional: true
    condition:
      field: useExistingRegistry
      operation: EQ
      value: 'false'
  - name: registryAuthSecret
    type: STRING
    documentation: Name of the secret in 'osbuilder' namespace that stores docker 'config.json' auth file.
    optional: true
    condition:
      field: isECRRegistry
      operation: EQ
      value: 'false'

  # Advanced configuration
  - name: advanced
    type: BOOL
    documentation: Show advanced configuration.

  - name: email
    type: STRING
    documentation: Optional Plural user email that will be attached to the autogenerated device bootstrap token. It will be visible in audit logs.
    optional: true
    condition:
      field: advanced
      operation: EQ
      value: 'true'
  - name: tag
    type: STRING
    documentation: Image tag that should be used when pushing to the registry.
    optional: true
    default: latest
    condition:
      field: advanced
      operation: EQ
      value: 'true'