apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: osbuilder
spec:
  name: osbuilder
  icon: https://user-images.githubusercontent.com/2420543/193010398-72d4ba6e-7efe-4c2e-b7ba-d3a826a55b7d.png
  identifier: mgmt
  documentation: |
    Sets up an osbuilder instance
  creates:
    git:
      ref: catalog/add-edge # TODO change to main
      folder: catalogs/edge/osbuilder
    templates:
    - source: helm
      destination: helm/osbuilder/{{ context.cluster }}
      external: true
    - source: servicedeployment.yaml
      destination: "bootstrap/apps/osbuilder/{{ context.cluster }}/servicedeployment.yaml"
      external: true
    - source: README.md
      destination: documentation/osbuilder/README.md
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: edge
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Setting up osbuilder on cluster {{ context.cluster }}"
  message: |
    Set up osbuilder on {{ context.cluster }}

    Will set up an osbuilder deployment.
  configuration:
  - name: cluster
    type: STRING
    documentation: Handle of the cluster you want to deploy osbuilder to.
    default: mgmt