apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: osbuilder
spec:
  name: osbuilder
  icon: https://user-images.githubusercontent.com/2420543/193010398-72d4ba6e-7efe-4c2e-b7ba-d3a826a55b7d.png
  identifier: mgmt
  documentation: |
    Sets up an osbuilder instance
  creates:
    git:
      ref: catalog/add-edge # TODO change to main
      folder: catalogs/edge/osbuilder
    templates:
    - source: helm
      destination: helm/osbuilder/{{ context.cluster }}
      external: true
      condition: "context.deploySelfHostedRegistry == true"
    - source: services/configuration.yaml.liquid
      destination: "services/apps/osbuilder/{{ context.cluster }}/configuration.yaml.liquid"
      external: true
    - source: services/generatedsecret.yaml.liquid
      destination: "services/apps/osbuilder/{{ context.cluster }}/generatedsecret.yaml.liquid"
      external: true
      condition: "context.deploySelfHostedRegistry == true"
    - source: "terraform/{{ context.cloud }}"
      destination: "terraform/apps/osbuilder/{{ context.cluster }}"
      external: true
      condition: "context.deploySelfHostedRegistry == true"
    - source: osbuilder-servicedeployment.yaml
      destination: "bootstrap/apps/osbuilder/{{ context.cluster }}/osbuilder-servicedeployment.yaml"
      external: true
    - source: osbuilder-stack.yaml
      destination: "bootstrap/apps/osbuilder/{{ context.cluster }}/osbuilder-stack.yaml"
      external: true
      condition: "context.deploySelfHostedRegistry == true"
    - source: osbuilder-raw-servicedeployment.yaml
      destination: "bootstrap/apps/osbuilder/{{ context.cluster }}/osbuilder-raw-servicedeployment.yaml"
      external: true
    - source: README.md
      destination: documentation/osbuilder/README.md
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: edge
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Setting up osbuilder on cluster {{ context.cluster }}"
  message: |
    Set up osbuilder on {{ context.cluster }}

    Will set up an osbuilder deployment.
  configuration:
  - name: cluster
    type: CLUSTER
    documentation: Cluster you want to deploy osbuilder to.
    default: mgmt
  - name: deploySelfHostedRegistry
    type: BOOL
    documentation: Whether you want to use your existing container registry or provision a self-hosted registry.
    default: 'false'

  # Self-hosted registry options
  - name: stackCluster
    type: CLUSTER
    documentation: Cluster used to run Infrastructure Stacks for provisioning the infrastructure.
    default: mgmt
    optional: true
    condition:
      field: deploySelfHostedRegistry
      operation: EQ
      value: 'true'
  - name: cloud
    type: ENUM
    documentation: Cloud provider you want to deploy osbuilder registry infrastructure to.
    optional: true
    condition:
      field: deploySelfHostedRegistry
      operation: EQ
      value: 'true'
    values:
      - aws
  - name: bucket
    type: STRING
    documentation: The name of the S3 Blob bucket you'll use as docker registry storage. This must be globally unique.
    optional: true
    condition:
      field: deploySelfHostedRegistry
      operation: EQ
      value: 'true'
  - name: hostname
    type: STRING
    documentation: The DNS name you'll host private docker registry under.
    optional: true
    condition:
      field: deploySelfHostedRegistry
      operation: EQ
      value: 'true'
  - name: region
    type: STRING
    documentation: The cloud provider region you're going to use to deploy cloud resources.
    optional: true
    condition:
      field: deploySelfHostedRegistry
      operation: EQ
      value: 'true'