{{- if (eq .Values.type "managed") -}}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    {{- include "workload-cluster.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "workload-cluster.dependsOnAnnotation" . | nindent 4 }}
spec:
  clusterName: {{ .Values.cluster.name }}
  {{- with .Values.cluster }}
  project: {{ .project }}
  location: {{ .region }}
  enableAutopilot: {{ .enableAutopilot | default false }}
  enableWorkloadIdentity: {{ .enableWorkloadIdentity }}
  {{- if ne .releaseChannel "unspecified" }}
  releaseChannel: {{ .releaseChannel }}
  {{- end }}
  endpoint:
    host: ""
    port: 0
  {{- end }}
  controlPlaneVersion: {{ trimPrefix "v" (.Values.cluster.kubernetesVersion | toString) }}
{{- end }}
