apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-master-key
  namespace: {% raw %}{{ .Release.Namespace }}{% endraw %}
type: Opaque
stringData:
  MEILI_MASTER_KEY: {% raw %}{{ .Values.masterKey | quote }}{% endraw %}
