apiVersion: v2
name: kubecost
description: Simple add-on to install kubecost agent in a tenant cluster
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kubecost-cloud-agent
    repository: https://kubecost.github.io/kubecost-cloud-agent/
    version: 1.0.0