apiVersion: deployments.plural.sh/v1alpha1
kind: PreviewEnvironmentTemplate
metadata:
  name: {{ context.name }}
spec:
  flowRef:
    name: {{ context.name }}

  referenceServiceRef:
    name: {{ context.name }}-dev
    namespace: {{ context.name }}
  
  template:
    namespace: "{{ context.name }}-pr-{% raw %}{{ pr.number }}{% endraw %}"
    name: "{{ context.name }}-pr-{% raw %}{{ pr.number }}{% endraw %}"
    helm:
      values:
        image:
          tag: {% raw %}"sha-{{ commitSha | slice: 0, 7 }}"{% endraw %}
