{{ if .Values.cloudflare }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-key
  labels:
{{ include "externaldns-addon.labels" . | indent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.cloudflare.key | quote }}
  email: {{ .Values.cloudflare.email | quote }}
{{ end }}