nameOverride: capz
fullnameOverride: ""

identity:
  clientId: ""
  clientSecret: ""
  tenantId: ""
  subscriptionId: ""

cluster-api-provider-azure:
  configVariables:
    exprimental:
      machinePool: true
  controllerManager:
    manager:
      image:
        repository: ghcr.io/kubernetes-sigs/cluster-api-azure-controller
        tag: v1.11.4
  asoControllerSettings:
    azureClientId: ""
    azureSubscriptionId: ""
    azureTenantId: ""
    azureClientSecret: ""