apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: plrl-01-grafana
  namespace: examples
spec:
  helm:
    url: https://grafana.github.io/helm-charts
    chart: grafana
    version: x.x.x
    values:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: plural
        ingressClassName: nginx
        hosts:
          - grafana-test.your-domain.com
        tls:
          - hosts:
              - grafana-test.your-domain.com
            secretName: grafana-tls
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: examples