resources:
  - wordpress
  - mysql

patches:
  - path: patch.yaml

replacements:
  - source:
      kind: Service
      name: wordpress
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: wordpress
        fieldPaths:
          - spec.template.spec.initContainers.[name=init-command].env.[name=WORDPRESS_SERVICE].value
  - source:
      kind: Service
      name: mysql
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: wordpress
        fieldPaths:
          - spec.template.spec.initContainers.[name=init-command].env.[name=MYSQL_SERVICE].value
          - spec.template.spec.containers.[name=wordpress].env.[name=WORDPRESS_DB_HOST].value

