apiVersion: deployments.plural.sh/v1alpha1
kind: GeneratedSecret
metadata:
  name: meilisearch-master-key-{{ context.cluster }}
  namespace: infra
spec:
  template:
    master_key: {% raw %}"{{ 48 | randAlphaNum }}"{% endraw %}
  destinations:
  - name: meilisearch-master-key-{{ context.cluster }}
    namespace: infra
  - name: meilisearch-master-key-{{ context.cluster }}
    namespace: plrl-deploy-operator
