apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: external-secrets
spec:
  name: external-secrets
  icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
  identifier: mgmt
  documentation: Sets up External Secrets Operator.
  creates:
    git:
      ref: main
      folder: catalogs/security/external-secrets
    templates:
      - source: README.md
        destination: documentation/external-secrets/README.md
        external: true
      - source: external-secrets.yaml
        destination: bootstrap/apps/external-secrets/external-secrets.yaml
        external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: security
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: External Secrets Operator setup
  message: Sets up External Secrets Operator.
  configuration: []
