apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: sealed-secrets
spec:
  name: sealed-secrets
  icon: https://avatars.githubusercontent.com/u/5446553?v=4
  identifier: mgmt
  documentation: Sets up Sealed Secrets controller.
  creates:
    git:
      ref: main
      folder: catalogs/security/sealed-secrets
    templates:
      - source: README.md
        destination: documentation/sealed-secrets/README.md
        external: true
      - source: sealed-secrets.yaml
        destination: bootstrap/apps/sealed-secrets/sealed-secrets.yaml
        external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: security
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: Sealed Secrets setup
  message: Sets up Sealed Secrets controller.
  configuration: []
