apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: trivy
spec:
  name: trivy
  icon: https://trivy.dev/latest/imgs/logo.png
  documentation: |
    Sets up an Trivy security scanner
  creates:
    git:
      ref: main
      folder: catalogs/security/trivy
    templates:
      - source: README.md
        destination: documentation/trivy/README.md
        external: true
      - source: servicedeployment.yaml.liquid
        destination: "bootstrap/apps/trivy/{{ context.cluster }}/servicedeployment.yaml"
        external: true
      - source: helm/values.yaml.liquid
        destination: helm/airbyte/{{ context.cluster }}.yaml.liquid
        external: true
#    - source: stack.yaml.liquid
#      destination: "bootstrap/apps/airbyte/{{ context.cluster }}/stack.yaml"
#      external: true
#    - source: terraform
#      destination: terraform/apps/airbyte
#      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: security
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Setting up Trivy on cluster {{ context.cluster }} for {{ context.cloud }}"
  message: |
    Set up Trivy on {{ context.cluster }} ({{ context.cloud }})

    Will set up an Trivy deployment
  configuration:
  - name: cluster
    type: STRING
    documentation: the cluster you want to deploy to
#  - name: cloud
#    type: ENUM
#    documentation: the cloud you can deploy airbyte to
#    values:
#    - aws
#  - name: bucket
#    type: STRING
#    documentation: the name of the S3/GCS/Azure Blob bucket you'll use for airbyte logs.  This must be globally unique
#  - name: hostname
#    type: STRING
#    documentation: the DNS name you'll host airbyte under
#  - name: region
#    type: STRING
#    documentation: the cloud region you're going to use for this instance
