apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: cluster-eks
spec:
  name: cluster-eks
  icon: https://cdn.icon-icons.com/icons2/2699/PNG/512/amazon_eks_logo_icon_168659.png
  identifier: mgmt
  documentation: |
    Sets up a PR to provision EKS cluster for a fleet + stage
  creates:
    git:
      ref: sebastian/prod-2981-set-up-catalog-pipeline # TODO set to main
      folder: catalogs/infra/cluster
    templates:
      - source: aws/stack.yaml
        destination: "services/infra/clusters/aws/stacks/{{ context.name }}.yaml"
        external: true
      - source: cluster.yaml
        destination: "services/infra/clusters/aws/{{ context.name }}.yaml"
        external: true
      - source: servicedeployment.yaml
        destination: "bootstrap/infra/clusters/servicedeployment.yaml"
        external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: infra
  scmConnectionRef:
    name: github  # you'll need to add this ScmConnection manually before this is functional
  title: "Adding EKS cluster: {{ context.name }}"
  message: "Adding EKS cluster {{ context.name }} and registering it with Plural"
  configuration:
    - name: name
      type: STRING
      documentation: Name of the cluster.
    - name: fleet
      type: STRING
      documentation: Name for the fleet you want this cluster to belong to.
    - name: tier
      type: ENUM
      documentation: What tier to place this cluster in.
      values:
        - dev
        - prd
    - name: region
      type: STRING
      documentation: Region where the cluster should be created.
    - name: credentialSecret
      type: STRING
      documentation: Name of the Kubernetes secret on the mgmt cluster in the infra namespace with the credentials that can be used to access the AWS cloud. It should contain 'AWS_ACCESS_KEY_ID' and 'AWS_SECRET_ACCESS_KEY' keys.
