apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: cluster-fleet-setup
spec:
  name: cluster-fleet-setup
  icon: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/d1a82b07-b809-4eb4-b615-8f24365b72b8/k8s.png?v=63861145828
  identifier: mgmt
  documentation: |
    Sets up a PR to a new fleet, with a dev + prod cluster and a pipeline to control upgrades
  creates:
    git:
      ref: main
      folder: catalogs/infra/cluster
    templates:
      - source: pipeline.yaml
        destination: "services/{{ context.fleet }}/setup/pipeline.yaml"
        external: true
      - source: services.yaml
        destination: "services/{{ context.fleet }}/setup/services.yaml"
        external: true
      - source: '{{ context.cloud }}/stack.yaml'
        destination: "services/{{ context.fleet }}/clusters/dev/{{ context.fleet }}-dev.yaml.liquid"
        context:
          tier: dev
        external: true
      - source: '{{ context.cloud }}/stack.yaml'
        destination: "services/{{ context.fleet }}/clusters/prod/{{ context.fleet }}-prod.yaml.liquid"
        context:
          tier: prod
        external: true
      - source: service.yaml
        destination: "bootstrap/infra/{{ context.fleet }}.yaml"
        external: true
      - source: pra.yaml
        destination: bootstrap/pr-automation/fleet-upgrade-pra.yaml
        external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: infra
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Setting up {{ context.cloud }} fleet {{ context.fleet }}"
  message: "Setting up {{ context.cloud }} fleet {{ context.fleet }}, including clusters and ugprade pipelines"
  configuration:
    - name: cloud
      type: ENUM
      documentation: Cloud where the clusters for this fleet should be created.
      values:
      - aws
      - azure
    - name: fleet
      type: STRING
      documentation: Name for the fleet you want this cluster to belong to.
    - name: region
      type: STRING
      documentation: Region where the cluster should be created.
    - name: resourceGroup
      type: STRING
      documentation: Azure resource group that you would like to use.
      optional: true
      condition:
        field: cloud
        operation: EQ
        value: 'azure'