apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: cluster-fleet-delete
spec:
  name: cluster-fleet-delete
  icon: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/d1a82b07-b809-4eb4-b615-8f24365b72b8/k8s.png?v=63861145828
  identifier: mgmt
  documentation: Sets up a PR to delete a cluster from the provided fleet
  deletes:
    files:
    - "bootstrap/infra/{{ context.fleet }}.yaml"
  catalogRef:
    name: infra
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Deletes fleet {{ context.fleet }}"
  message: "Deletes fleet {{ context.fleet }}"
  configuration:
    - name: fleet
      type: STRING
      documentation: Name for the fleet you this cluster to belongs to