{{- if (eq .Values.type "managed") -}}
kind: AWSManagedCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    helm.sh/resource-policy: keep
spec: {}
{{- end }}