apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    {{- include "workload-cluster.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterNetwork:
    {{- with .Values.cluster.podCidrBlocks }}
    pods:
      cidrBlocks: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cluster.serviceCidrBlocks }}
    services:
      cidrBlocks: {{ toYaml . | nindent 6 }}
    {{- end }}
  infrastructureRef:
    kind: AWSManagedCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    name: {{ .Values.cluster.name }}
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    name: {{ .Values.cluster.name }}
