apiVersion: v2
name: flux-source-controller
description: Flux Source Controller
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: flux2
  repository: https://fluxcd-community.github.io/helm-charts
  version: 2.11.1