# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

flux2:
  helmController:
    create: false
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false