apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: postgres-{{ context.name }}
  namespace: apps
spec:
{% if context.ai %}
  agentId: {{ context.ai.session.agent_id }}
{% endif %}
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  git:
    ref: main
    folder: terraform/apps/postgres/{{ context.name }}
  repositoryRef:
    name: infra
    namespace: infra
  variables:
    network: {{ context.network }}
    name: {{ context.name }}
  {% if context.cloud == 'azure' %}
  jobSpec:
    namespace: plrl-deploy-operator
    labels:
      azure.workload.identity/use: "true"
    serviceAccount: "stacks"
  {% endif %}
  clusterRef:
    name: mgmt
    namespace: infra
