apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
    type: eBPF
    ebpf:
      sampling: 50
      logLevel: info
      privileged: false
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 800Mi
  processor:
    logLevel: info
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 800Mi
    logTypes: Flows
    advanced:
      conversationEndTimeout: 10s
      conversationHeartbeatInterval: 30s
  prometheus:
    querier:
      enable: true
      mode: Auto
      timeout: 60s
  consolePlugin:
    enable: true
    imagePullPolicy: IfNotPresent
    logLevel: info
    replicas: 1
    autoscaler:
      status: Disabled
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
    portNaming:
      enable: true
      portNames:
        "3100": loki
    quickFilters:
      - name: Applications
        filter:
          flow_layer: 'app'
        default: true
      - name: Infrastructure
        filter:
          flow_layer: 'infra'
      - name: Pods network
        filter:
          src_kind: 'Pod'
          dst_kind: 'Pod'
        default: true
      - name: Services network
        filter:
          dst_kind: 'Service'
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
      limits:
        memory: 100Mi
  exporters: []
