apiVersion: v2
name: ingress-nginx
description: wrapper chart for the ingress nginx controller
type: application
version: 0.1.0
appVersion: "1.7.0"
dependencies:
- name: ingress-nginx
  version: 4.6.0
  repository: https://kubernetes.github.io/ingress-nginx