# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  leaderElection:
    namespace: cert-manager
  
  podDnsPolicy: "None"
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
      - "8.8.8.8"

ownerEmail: someone@example.com
ingressClass: nginx

cert-manager:
  installCRDs: true
