# Default values for kubecost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  thanos:
    enabled: false 
  grafana:
    enabled: false 
    proxy: false

kubecost-cloud-agent:
  cloudAgent: true 
  cloudAgentTLSFileName: "files/prod-cloud-cert.pem"
  cloudAgentTLSCertName: "agent-tls-public-key"
  imageVersion: lunar-sandwich.v0.1.2
  cloudReportingServer: collector.app.kubecost.com:31357
  networkCosts:
    enabled: true

  podSecurityPolicy: 
    enabled: false

  prometheus:
    podSecurityPolicy: 
      enabled: false
    nodeExporter:
      enabled: false
    kube-state-metrics:
      enabled: false
      disabled: true
    extraScrapeConfigs: |
      - job_name: kubecost-cloud-agent
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 60s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - {{ .Release.Name }}-cloud-agent
          type: 'A'
          port: 9005
      - job_name: kubecost-networking
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
        # Scrape only the the targets matching the following metadata
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex:  {{ template "cost-analyzer.networkCostsName" . }}


  kubecostMetrics: 
    exporter:
      enabled: true 
      exportClusterInfo: false
      exportClusterCache: false

  grafana:
    sidecar:
      dashboards:
        enabled: false
      datasources:
        defaultDatasourceEnabled: false

  kubecostFrontend:
    enabled: false
  kubecostToken: CHANGEME