apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: osartifact-{{ context.name }}-{{ context.cluster }}
  namespace: apps
spec:
  namespace: osbuilder
  git:
    folder: helm/osartifact/{{ context.cluster }}/{{ context.name }}
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "0.x.x"
    chart: osartifact
    release: plural-edge-{{ context.name }}
    url: https://pluralsh.github.io/osbuilder/
    valuesFiles:
      - osartifact.yaml.liquid
  configuration:
    name: {{ context.name }}
    image: {{ context.image }}
    device: {{ context.device }}
    username: {{ context.username }}
    email: {{ context.email }}
    project: {{ context.project }}
    url: {{ context.url }}
  clusterRef:
    kind: Cluster
    name: {{ context.cluster }}
    namespace: infra
