apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: osartifact-{{ context.name }}-{{ context.cluster }}
  namespace: apps
spec:
  namespace: osbuilder
  git:
    folder: helm/osartifact/{{ context.cluster }}/{{ context.name }}
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  helm:
    version: "0.x.x"
    chart: osartifact
    release: plural-edge-{{ context.name }}
    url: https://pluralsh.github.io/osbuilder/
    valuesFiles:
      - osartifact.yaml.liquid
  configurationRef:
    name: osbuilder-{{ context.cluster }}-configuration
  configuration:
    cluster: {{ context.cluster }}
    name: {{ context.name }}
    image: {{ context.image }}
    device: {{ context.device }}
    username: {{ context.username }}
    {% if context.registry %}registry: {{ context.registry }}{% endif %}
    {% if context.repository %}repository: {{ context.repository }}{% endif %}
    {% if context.endif %}tag: {{ context.tag }}{% endif %}
  clusterRef:
    kind: Cluster
    name: {{ context.cluster }}
    namespace: infra
