apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: osartifact-{{ context.name }}-{{ context.cluster }}
  namespace: apps
spec:
  namespace: osbuilder
  git:
    folder: services/apps/osartifact
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  configuration:
    cluster: {{ context.cluster }}
    name: {{ context.name }}
    image: {{ context.image }}
    device: {{ context.device }}
    username: {{ context.username }}
    password: {{ context.password }}
    url: {{ context.url }}
    token: {{ context.token }}
  clusterRef:
    kind: Cluster
    name: {{ context.cluster }}
    namespace: infra
