apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: osbuilder-raw-{{ context.cluster }}
  namespace: apps
spec:
  namespace: osbuilder
  git:
    folder: services/apps/osbuilder/{{ context.cluster }}
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  clusterRef:
    kind: Cluster
    name: {{ context.cluster }}
    namespace: infra
