apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: flow-postgres
spec:
  name: flow-postgres
  icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
  identifier: mgmt
  documentation: Sets up a Plural Flow to manage the deployment of an application backed by a postgres database
  creates:
    git:
      ref: main
      folder: catalogs/apps
    templates:
    - source: postgres/flow
      destination: "services/flows/postgres"
      external: true
    - source: postgres/terraform
      destination: "terraform/flows/postgres"
      external: true
    - source: postgres/setup.yaml
      destination: "bootstrap/flows/{{ context.name }}.yaml"
      external: true
    - source: flow-upgrade-pra.yaml
      destination: "bootstrap/pr-automation/flow-upgrade-pra.yaml"
      external: true
    - source: postgres/helm/postgres.values.yaml.liquid
      destination: helm/flows/postgres.values.yaml.liquid
      external: true
    - source: README.md
      destination: "documentation/flows/README.md"
      external: true
  repositoryRef:
    name: scaffolds
  catalogRef:
    name: apps
  scmConnectionRef:
    name: plural  # you'll need to add this ScmConnection manually before this is functional
  title: "Setting up a postgres based application {{ context.name }} from clusters {{ context.devCluster }} to {{ context.prodCluster }}"
  message: |
    Setting up a postgres based application {{ context.name }}

    dev cluster: {{ context.devCluster }}
    prod cluster: {{ context.prodCluster }}
    registry: {{ context.registry }}
    tag: {{ context.tag }}
  configuration:
  - name: name
    type: STRING
    documentation: The name of the flow this will create.
  - name: group
    type: STRING
    documentation: The Plural user group to give write access to this flow.
    default: "sre"
  - name: cloud
    type: ENUM
    documentation: The cloud provider you want to deploy to.
    values:
    - aws
    - azure
    - gcp
  - name: devCluster
    type: CLUSTER
    documentation: Handle of the dev cluster you want to deploy to.
  - name: prodCluster
    type: CLUSTER
    documentation: Handle of the prod cluster you want to deploy to.
  - name: registry
    type: STRING
    documentation: The name of the docker image registry you'll use to deploy the application.
  - name: tag
    type: STRING
    documentation: The docker tag you'll use to deploy the application.
  - name: devDomain
    type: STRING
    documentation: The domain name you'll use to access the application in the dev cluster.
  - name: prodDomain
    type: STRING
    documentation: The domain name you'll use to access the application in the prod cluster.
