apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: {{ context.fleet }}-dev
spec:
{% if context.ai %}
  agentId: {{ context.ai.session.agent_id }}
{% endif %}
  namespace: infra
  git:
    folder: services/{{ context.fleet }}/clusters/dev
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  configuration:
    kubernetesVersion: '1.32' # dev
  clusterRef:
    name: mgmt
    namespace: infra
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: {{ context.fleet }}-prod
spec:
{% if context.ai %}
  agentId: {{ context.ai.session.agent_id }}
{% endif %}
  namespace: infra
  git:
    folder: services/{{ context.fleet }}/clusters/prod
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  configuration:
    kubernetesVersion: '1.32' # prod
  clusterRef:
    name: mgmt
    namespace: infra
