apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: {{ context.fleet }}-setup
  namespace: infra
spec:
{% if context.ai %}
  agentId: {{ context.ai.session.agent_id }}
{% endif %}
  namespace: infra
  git:
    folder: services/{{ context.fleet }}/setup
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
