apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: {{ context.fleet }}-setup
  namespace: infra
spec:
  namespace: infra
  git:
    folder: services/{{ context.fleet }}/setup
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
