apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: {{ context.fleet }}-dev
  namespace: infra
spec:
  namespace: {{ context.fleet }}
  git:
    folder: services/{{ context.fleet }}/clusters/dev
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  configuration:
    kubernetesVersion: '1.29' # dev
  clusterRef:
    name: mgmt
    namespace: infra
---
apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: {{ context.fleet }}-prod
  namespace: infra
spec:
  namespace: {{ context.fleet }}
  git:
    folder: services/{{ context.fleet }}/clusters/prod
    ref: main
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  configuration:
    kubernetesVersion: '1.29' # prod
  clusterRef:
    name: mgmt
    namespace: infra
