apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: cloud-functions-{{ context.name }}
  namespace: apps
spec:
{% if context.ai %}
  agentId: {{ context.ai.session.agent_id }}
{% endif %}
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  git:
    ref: main
    folder: terraform/apps/cloud-functions/{{ context.name }}
  repositoryRef:
    name: infra
    namespace: infra
  variables:
    name: "{{ context.name }}"
    region: "{{ context.region }}"
    cloud_connection_id: "{{ context.cloudConnectionId }}"
    artifact_version: "{{ context.version }}"
    {% if context.invokerServiceAccount %}
    invoker_service_account: "{{ context.invokerServiceAccount }}"
    {% endif %}
  {% if context.cloud == 'azure' %}
  jobSpec:
    namespace: plrl-deploy-operator
    labels:
      azure.workload.identity/use: "true"
    serviceAccount: "stacks"
  {% endif %}
  clusterRef:
    name: mgmt
    namespace: infra
