{{- $name := .Values.cluster.name -}}
{{- $v := .Values.cluster.vsphere -}}
{{- $podCidr := (index .Values.cluster.podCidrBlocks 0) | default .Values.addons.cni.podCidr -}}
{{- if .Values.addons.cni.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-cni-flannel
  labels:
    {{- include "workload-cluster.labels" . | nindent 4 }}
data:
  flannel.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kube-flannel
      labels:
        k8s-app: flannel
        pod-security.kubernetes.io/enforce: privileged
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        k8s-app: flannel
      name: flannel
      namespace: kube-flannel
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        k8s-app: flannel
      name: flannel
    rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["nodes/status"]
      verbs: ["patch"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        k8s-app: flannel
      name: flannel
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: flannel
    subjects:
    - kind: ServiceAccount
      name: flannel
      namespace: kube-flannel
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kube-flannel-cfg
      namespace: kube-flannel
      labels:
        tier: node
        app: flannel
        k8s-app: flannel
    data:
      cni-conf.json: |
        {
          "name": "cbr0",
          "cniVersion": "0.3.1",
          "plugins": [
            {
              "type": "flannel",
              "delegate": {
                "hairpinMode": true,
                "isDefaultGateway": true
              }
            },
            {
              "type": "portmap",
              "capabilities": { "portMappings": true }
            }
          ]
        }
      net-conf.json: |
        {
          "Network": "{{ $podCidr }}",
          "EnableNFTables": false,
          "Backend": { "Type": "vxlan" }
        }
    ---
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: kube-flannel-ds
      namespace: kube-flannel
      labels:
        tier: node
        app: flannel
        k8s-app: flannel
    spec:
      selector:
        matchLabels:
          app: flannel
      template:
        metadata:
          labels:
            tier: node
            app: flannel
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values: ["linux"]
          hostNetwork: true
          priorityClassName: system-node-critical
          tolerations:
          - operator: Exists
            effect: NoSchedule
          serviceAccountName: flannel
          initContainers:
          - name: install-cni-plugin
            image: ghcr.io/flannel-io/flannel-cni-plugin:v1.9.1-flannel2
            command: ["cp"]
            args: ["-f", "/flannel", "/opt/cni/bin/flannel"]
            volumeMounts:
            - name: cni-plugin
              mountPath: /opt/cni/bin
          - name: install-cni
            image: ghcr.io/flannel-io/flannel:v0.28.7
            command: ["/opt/bin/install-conf"]
            args: ["/etc/kube-flannel/cni-conf.json", "/etc/cni/net.d/10-flannel.conflist"]
            volumeMounts:
            - name: cni
              mountPath: /etc/cni/net.d
            - name: flannel-cfg
              mountPath: /etc/kube-flannel/
          containers:
          - name: kube-flannel
            image: ghcr.io/flannel-io/flannel:v0.28.7
            command: ["/opt/bin/flanneld"]
            args: ["--ip-masq", "--kube-subnet-mgr"]
            resources:
              requests:
                cpu: 100m
                memory: 50Mi
            securityContext:
              capabilities:
                add: ["NET_ADMIN", "NET_RAW"]
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: run
              mountPath: /run/flannel
            - name: flannel-cfg
              mountPath: /etc/kube-flannel/
            - name: xtables-lock
              mountPath: /run/xtables.lock
          volumes:
          - name: run
            hostPath:
              path: /run/flannel
          - name: cni-plugin
            hostPath:
              path: /opt/cni/bin
          - name: cni
            hostPath:
              path: /etc/cni/net.d
          - name: flannel-cfg
            configMap:
              name: kube-flannel-cfg
          - name: xtables-lock
            hostPath:
              path: /run/xtables.lock
              type: FileOrCreate
---
{{- end }}
{{- if .Values.addons.cpi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-cpi-vsphere
  labels:
    {{- include "workload-cluster.labels" . | nindent 4 }}
data:
  cpi.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cloud-controller-manager
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: system:cloud-controller-manager
    rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch", "update"]
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["nodes/status"]
      verbs: ["patch"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["list", "patch", "update", "watch"]
    - apiGroups: [""]
      resources: ["services/status"]
      verbs: ["list", "patch", "update", "watch"]
    - apiGroups: [""]
      resources: ["persistentvolumes"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: ["create", "patch", "update"]
    - apiGroups: [""]
      resources: ["serviceaccounts"]
      verbs: ["create", "get"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["create", "get", "list", "watch"]
    - apiGroups: ["coordination.k8s.io"]
      resources: ["leases"]
      verbs: ["create", "get", "list", "watch", "update"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: system:cloud-controller-manager
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:cloud-controller-manager
    subjects:
    - kind: ServiceAccount
      name: cloud-controller-manager
      namespace: kube-system
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: vsphere-cloud-secret
      namespace: kube-system
    type: Opaque
    stringData:
      {{ $v.server }}.username: {{ $v.identity.username | quote }}
      {{ $v.server }}.password: {{ $v.identity.password | quote }}
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: vsphere-cloud-config
      namespace: kube-system
    data:
      vsphere.conf: |
        global:
          secretNamespace: kube-system
          secretName: vsphere-cloud-secret
          {{- if $v.thumbprint }}
          thumbprint: {{ $v.thumbprint | quote }}
          {{- end }}
        vcenter:
          {{ $v.server }}:
            server: {{ $v.server }}
            datacenters:
            - {{ $v.datacenter }}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vsphere-cloud-controller-manager
      namespace: kube-system
      labels:
        app: vsphere-cloud-controller-manager
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: vsphere-cloud-controller-manager
      template:
        metadata:
          labels:
            app: vsphere-cloud-controller-manager
        spec:
          serviceAccountName: cloud-controller-manager
          tolerations:
          - key: node.cloudprovider.kubernetes.io/uninitialized
            effect: NoSchedule
            value: "true"
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
          - key: node.kubernetes.io/not-ready
            effect: NoSchedule
          securityContext:
            runAsUser: 1001
          containers:
          - name: vsphere-cloud-controller-manager
            image: {{ .Values.addons.cpi.image }}
            args:
            - --cloud-provider=vsphere
            - --v=2
            - --cloud-config=/etc/cloud/vsphere.conf
            volumeMounts:
            - name: cloud-config
              mountPath: /etc/cloud
              readOnly: true
          volumes:
          - name: cloud-config
            configMap:
              name: vsphere-cloud-config
---
{{- end }}
{{- if or .Values.addons.cni.enabled .Values.addons.cpi.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: {{ $name }}-addons
  labels:
    {{- include "workload-cluster.labels" . | nindent 4 }}
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ $name }}
  resources:
  {{- if .Values.addons.cni.enabled }}
  - name: {{ $name }}-cni-flannel
    kind: ConfigMap
  {{- end }}
  {{- if .Values.addons.cpi.enabled }}
  - name: {{ $name }}-cpi-vsphere
    kind: ConfigMap
  {{- end }}
{{- end }}
