apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    {{- include "workload-cluster.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  username: {{ .Values.cluster.vsphere.identity.username | required "cluster.vsphere.identity.username is required" | quote }}
  password: {{ .Values.cluster.vsphere.identity.password | required "cluster.vsphere.identity.password is required" | quote }}
