apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: plrl-04-extras
  namespace: examples
spec:
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  git:
    folder: services/examples/helm-with-kustomize
    ref: main
  configurationRef:
    name: plrl-04-wordpress-config
    namespace: examples
  clusterRef:
    name: mgmt
    namespace: examples