apiVersion: v2
name: plrl-github-actions-runner
description: a wrapper chart to deploy a github actions runner set
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: gha-runner-scale-set
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
  version: '>= 0.0.0'