# Default values for github-actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
gha-runner-scale-set:
  controllerServiceAccount:
    name: github-actions-controller-gha-rs-controller
    namespace: github-actions-controller
  containerMode:
    type: kubernetes
    template:
      spec:
        securityContext:
          fsGroup: 123
        containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
        volumes:
        - name: work
          emptyDir: {}
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
      storageClassName: "dynamic-blob-storage"
      resources:
        requests:
          storage: 1Gi