# Default values for github-actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
gha-runner-scale-set:
  controllerServiceAccount:
    name: github-actions-controller-gha-rs-controller
    namespace: github-actions-controller
  template:
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
        env:
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
  containerMode:
    type: kubernetes
    kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 1Gi