# Default values for github-actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
gha-runner-scale-set:
  controllerServiceAccount:
    name: github-actions-controller-gha-rs-controller
    namespace: github-actions-controller