apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: trigger-upgrade-mgmt-cluster
spec:
  name: trigger-upgrade-mgmt-cluster
  documentation: triggers a stack to upgrade the mgmt cluster 
  updates:
    regexReplacements:
    - regex: '(kubernetes_version = )"(.*)" # k8s version'
      file: "terraform/mgmt/mgmt.tf"
      replacement: '(kubernetes_version = )"{{ context.version }}" # k8s version'
  repositoryRef:
    name: plrl-mgmt
  catalogRef:
    name: plural-upgrade
  scmConnectionRef:
    name: github
  title: "Plural Stack: Mgmt"
  message: "Plural Stack: mgmt"
  identifier: pluralsh/plrl-mgmt
  configuration:
  - name: version
    type: STRING
    documentation: the new k8s version to use