apiVersion: deployments.plural.sh/v1alpha1
kind: PrAutomation
metadata:
  name: trigger-upgrade-dedicated-cluster
spec:
  name: trigger-upgrade-dedicated-cluster
  documentation: triggers a stack to upgrade the dedicated cluster 
  updates:
    regexReplacements::
    - regex: 'default = "(.*)" # k8s version'
      file: "terraform/modules/dedicated/aws/variables.tf"
      replacement: 'default = "{{ context.version }}" # k8s version'
  repositoryRef:
    name: plrl-mgmt
  catalogRef:
    name: plural-upgrade
  scmConnectionRef:
    name: github
  title: "Plural Stack: Dedicated"
  message: "Plural Stack: dedicated-nimbus"
  identifier: pluralsh/plrl-mgmt
  configuration:
  - name: version
    type: STRING
    documentation: the new k8s version to use