kind: AzureManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.cluster.clusterIdentity -}}
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: {{ .Values.cluster.clusterIdentity.name }}
    namespace: {{ .Release.Namespace }}
  {{- else }}
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: "default-identity" # Refers to the identity created in the capi/providers/azure/templates/identity.yaml.
    namespace: {{ .Release.Namespace }}
  {{- end }}
  location: {{ .Values.cluster.location }}
  resourceGroupName: {{ .Values.cluster.resourceGroupName }}
  nodeResourceGroupName: {{ .Values.cluster.nodeResourceGroupName }}
  subscriptionID: {{ .Values.cluster.subscriptionID }}
  version: {{ .Values.cluster.kubernetesVersion }}
  {{- with .Values.cluster.virtualNetwork }}
  virtualNetwork:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  networkPlugin: {{ .Values.cluster.networkPlugin }}
  networkPolicy: {{ .Values.cluster.networkPolicy }}
  outboundType: {{ .Values.cluster.outboundType }}
  dnsServiceIP: {{ .Values.cluster.dnsServiceIP }}
  {{- with .Values.cluster.identity }}
  identity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.sku }}
  sku:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  loadBalancerSKU: {{ .Values.cluster.loadBalancerSKU }}
  {{- with .Values.cluster.oidcIssuerProfile }}
  oidcIssuerProfile:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.aadProfile }}
  aadProfile:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.loadBalancerProfile }}
  loadBalancerProfile:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.apiServerAccessProfile }}
  apiServerAccessProfile:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.autoscalerProfile }}
  autoscalerProfile:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.addonProfiles }}
  addonProfiles:
    {{- toYaml . | nindent 4 }}
  {{- end }}
