apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterNetwork:
    {{- with .Values.cluster.podCidrBlocks }}
    pods:
      cidrBlocks: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cluster.serviceCidrBlocks }}
    services:
      cidrBlocks: {{ toYaml . | nindent 6 }}
    {{- end }}
  infrastructureRef:
    kind: {{ include "cluster.infrastructure.kind" . }}
    apiVersion: {{ include "cluster.infrastructure.apiVersion" . }}
    name: {{ .Values.cluster.name }}
  controlPlaneRef:
    kind: {{ include "cluster.controlPlane.kind" . }}
    apiVersion: {{ include "cluster.controlPlane.apiVersion" . }}
    name: {{ .Values.cluster.name }}
