apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: plrl-04-wordpress
  namespace: examples
spec:
  repositoryRef:
    kind: GitRepository
    name: infra
    namespace: infra
  git:
    folder: services/examples/kustomize-inflate-helm
    ref: main
  kustomize:
    path: '.'
    enableHelm: true
  configurationRef:
    name: plrl-04-wordpress-config
    namespace: examples
  clusterRef:
    name: floreks-kind
    namespace: examples