name: Test Catalogs

on:
  pull_request:
    branches:
    - main

jobs:
  test-pras:
    name: test pras
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - uses: actions/checkout@v7
        name: checkout repo
        with:
          persist-credentials: false
      
      - uses: extractions/setup-just@v4
      - uses: pluralsh/setup-plural@v2
        with:
          vsn: 0.11.0
          
      - run: just test
