apiVersion: v2
name: kube-state-metrics
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 2.10.0
dependencies:
  - name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: 5.14.0
